spring.application.name=demo

# Configuración de la conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_db
spring.datasource.username=postgresql
spring.datasource.password=postgres

# Configuración del proveedor de la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver

# Otras propiedades de configuración de la base de datos
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
