spring.application.name=demo

# Configuraci贸n de la conexi贸n a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuraci贸n del proveedor de la base de datos
spring.datasource.driver-class-name=org.postgresql.Driver

# Otras propiedades de configuraci贸n de la base de datos
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Muestra las queries SQL que ejecuta Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Nivel de log m醩 detallado (muestra valores en las consultas)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
